EXTRA_CFLAGS += -I$(src)/../common/

obj-m := sassy_core.o sassy_core_ctrl.o pm.o net.o proto.o sassy_payload_helper.o
obj-m += event_logger/event_logger.o event_logger/event_logger_ctrl.o 
pm-objs := pm/sassy_pm.o pm/sassy_pm_ctrl.o
net-objs := net/sassy_net.o

proto-objs := proto/proto_mgmt.o proto/proto_instance_ctrl.o 


obj-m += ts/

