---
- hosts: testnodes
  tasks:

    # -- Prepare install Env  --------------------------------------
    - name: Install dpdk build dependencies
      apt:
        pkg:
          - build-essential
          - pkgconf
          - python3
          - python3-pip
          - ninja-build
          - libjansson-dev
          - libbsd-dev
          - libnuma-dev
          - libssl-dev
          - zlib1g-dev
          - libpcap-dev
          - libibverbs-de
      become: yes

    # -- Install Asgard kernel ------------------------------------------------------------

